### ISSUE TITLE
Static analysis

### ISSUE THREAD

**Issue by szepeviktor** [tarosky/logbook#6]
Hello @miya0001 !

Try running @phpstan on your nice code.

`composer require --dev phpstan/phpstan-shim szepeviktor/phpstan-wordpress`

phpstan.neon.dist

```yaml
includes:
    - phar://phpstan.phar/conf/bleedingEdge.neon
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    level: max
    paths:
        - %currentWorkingDirectory%/src/
    ignoreErrors:
        # Uses func_get_args()
        - '#^Function add_query_arg invoked with [123] parameters?, 0 required\.$#'
        # __get()
        - '#^Access to an undefined property WP_CLI\\Formatter::\$format\.$#'
```
